spring.application.name=SpringBootMailSenderDemo
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=linginenirohithkumar@gmail.com
spring.mail.password=zexinkgkypfksiiz

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
